// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentalShop.Domain.States;
using RentalShop.Infrastructure.Persistence;

#nullable disable

namespace RentalShop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    [Migration("20260506134758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentalShop.Domain.Entities.PackageComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentPackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentPackageId");

                    b.ToTable("PackageComponents", (string)null);

                    b.HasDiscriminator<string>("ComponentType").HasValue("PackageComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RentalShop.Domain.Entities.RentalItem", b =>
                {
                    b.Property<string>("Sku")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("BasePricePerDay")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("AvailableState")
                        .HasColumnName("CurrentStateName");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Sku");

                    b.ToTable("RentalItems", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("RentalItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RentalShop.Domain.Entities.RentalLineItem", b =>
                {
                    b.HasBaseType("RentalShop.Domain.Entities.PackageComponent");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasDiscriminator().HasValue("LineItem");
                });

            modelBuilder.Entity("RentalShop.Domain.Entities.RentalPackage", b =>
                {
                    b.HasBaseType("RentalShop.Domain.Entities.PackageComponent");

                    b.HasDiscriminator().HasValue("Package");
                });

            modelBuilder.Entity("RentalShop.Domain.Entities.GearItem", b =>
                {
                    b.HasBaseType("RentalShop.Domain.Entities.RentalItem");

                    b.HasDiscriminator().HasValue("Gear");

                    b.HasData(
                        new
                        {
                            Sku = "GEAR-001",
                            BasePricePerDay = 22m,
                            CurrentState = "AvailableState",
                            Name = "Camping Tent"
                        },
                        new
                        {
                            Sku = "GEAR-002",
                            BasePricePerDay = 8m,
                            CurrentState = "AvailableState",
                            Name = "Sleeping Bag"
                        },
                        new
                        {
                            Sku = "GEAR-003",
                            BasePricePerDay = 35m,
                            CurrentState = "AvailableState",
                            Name = "Kayak"
                        });
                });

            modelBuilder.Entity("RentalShop.Domain.Entities.ToolItem", b =>
                {
                    b.HasBaseType("RentalShop.Domain.Entities.RentalItem");

                    b.HasDiscriminator().HasValue("Tool");

                    b.HasData(
                        new
                        {
                            Sku = "TOOL-001",
                            BasePricePerDay = 12m,
                            CurrentState = "AvailableState",
                            Name = "Cordless Drill"
                        },
                        new
                        {
                            Sku = "TOOL-002",
                            BasePricePerDay = 18m,
                            CurrentState = "AvailableState",
                            Name = "Circular Saw"
                        },
                        new
                        {
                            Sku = "TOOL-003",
                            BasePricePerDay = 6m,
                            CurrentState = "AvailableState",
                            Name = "Hammer-set"
                        });
                });

            modelBuilder.Entity("RentalShop.Domain.Entities.PackageComponent", b =>
                {
                    b.HasOne("RentalShop.Domain.Entities.RentalPackage", null)
                        .WithMany("_children")
                        .HasForeignKey("ParentPackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RentalShop.Domain.Entities.RentalPackage", b =>
                {
                    b.Navigation("_children");
                });
#pragma warning restore 612, 618
        }
    }
}
