using RentalShop.Domain.Entities;

namespace RentalShop.Application.Factories
{
    /// <summary>
    /// Represents the abstract 'Creator' in the Factory Method GoF pattern —
    /// declares the factory method but defers instantiation to subclasses.
    ///
    /// Domain role: base contract for catalog item factories. The shop
    /// onboards new rental categories by subclassing this factory rather than
    /// editing a central instantiation switch. SKU generation is the factory's
    /// responsibility; callers supply only business-meaningful data.
    /// </summary>
    public abstract class ItemFactory
    {
        /// <summary>
        /// Auto-template variant: creates an item using the factory's built-in
        /// template pool. Both name and SKU are auto-generated.
        /// </summary>
        public abstract RentalItem Create();

        /// <summary>
        /// User-named variant: creates an item with a caller-supplied name and
        /// price. The SKU is still auto-generated by the factory so the
        /// uniqueness and formatting contract is always enforced.
        /// </summary>
        public abstract RentalItem Create(string name, decimal price);
    }
}
